### ISSUE TITLE
help: 

### ISSUE THREAD

**Issue by maximepvrt** [harlan-zw/nuxt-seo-utils#27]
### 📚 What are you trying to do?

I want to set default SEO meta values, such as `ogImage`, using `useSeoMeta` in `app.vue`, while also using SEO Route Rules to define Open Graph properties for all subpages of a folder as described in the [[Route Rules guide](https://nuxtseo.com/docs/seo-utils/guides/route-rules)](https://nuxtseo.com/docs/seo-utils/guides/route-rules).  

### 🔍 What have you tried?

I set default meta values in `app.vue` using `useSeoMeta`, but when applying SEO Route Rules to define Open Graph properties for subpages of a folder, the rules are ignored.  
However, if I remove the Open Graph definitions in `app.vue`, the SEO Route Rules work as expected.  
I’ve checked the documentation and examples, but I couldn’t find a solution for combining both approaches.  

### ℹ️ Additional context

Here’s a simplified version of my setup:  

In `app.vue`:  
```javascript
useSeoMeta({
  ogImage: '/default-image.png',
});
```

In `nuxt.config.ts`:  
```javascript
routeRules: {
  '/folder/**': {
    seo: {
      ogImage: '/folder-specific-image.png',
    },
  },
},
```

When `ogImage` is defined in `app.vue`, it seems to override or ignore the Route Rules.  
Let me know if I’m missing something or if there’s a specific way to prioritize Route Rules over defaults.

**Comment by harlan-zw** [comment]
Hey, thanks for the issue. It looks like you're trying to set a default og image for a directory, can I suggest using the [OG Image App Icons](https://nuxtseo.com/docs/seo-utils/guides/open-graph-images#opengraph-image) instead? This will properly handle all of the tags for you.

I've pushed up a fix for the route rules either way, giving them higher priority by default. I've also improved the docs.

**Comment by harlan-zw** [comment]
This is a good point, I'm not too sure how to solve this as if we use route rules client-side we then need to wait for the Nuxt manifest to download before hydration which has a slight performance cost. Some Nuxt sites may already be loading this immediately though.

I'll merge your PR for now and think about this.
