### ISSUE TITLE
feat: redirectToCanonicalSiteUrl is incompatible with nuxt-graphql-middleware

### ISSUE THREAD

**Issue by luksak** [harlan-zw/nuxt-seo-utils#33]
### 🆒 Your use case

I'm using `nuxt-seo-utils` with `redirectToCanonicalSiteUrl` enabled together with `nuxt-graphql-middleware`. It was working when using `nuxt-seo-experiments`, but after upgrading to `nuxt-seo-utils` this broke the apis provided by `nuxt-graphql-middleware`. It would be great to have those two module work together.

Sadly I can't provide more background, since I currently can't reproduce this behaviour locally. I only see it on a test environment where I don't have access to the logs.

### 🆕 The solution you'd like

- Disable redirects for routes where this module causes issues
- An option to disable canonical redirects for certain routes using configuration. That would make it possible for `nuxt-graphql-middleware` and other projects to disable redirects for their routes.

### 🔍 Alternatives you've considered

Disabling `redirectToCanonicalSiteUrl` fixes the API

### ℹ️ Additional info

I'm using nuxt-seo-utils `6.0.3` and nuxt-graphql-middleware `4.3.1`

**Comment by harlan-zw** [comment]
Thanks for the issue, I think the easiest option, for now, is not to redirect any "internal routes" (`/api/*` or `/_nuxt/*`) which I've pushed up a fix for.
