### ISSUE TITLE
fix: i18n breadcrumb override

### ISSUE THREAD

**Issue by v-moravec** [harlan-zw/nuxt-seo-utils#34]
### 🐛 The bug

https://github.com/harlan-zw/nuxt-seo-utils/blob/main/src/runtime/app/composables/useBreadcrumbItems.ts#L160

This results in '<route-name>,<locale-name>' string - which disables the option to customize page names.

route.name download___de
routeName download,de

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-daze4uq2?file=pages%2Findex.vue

### 🌈 Expected behavior

I believe the ',de' should not be there. Then translation of labels should work again.

**Comment by harlan-zw** [comment]
Thanks for the detailed issue and reproduction. I've pushed up a fix for this with a test.
